# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9e71026218005feb03a6483b184a0cb3f7f38e81df56b6513313e0a390098e91be980dd82ea4de98b66249ec082b112cb798578d1dbc91534d8a73d4e4587a4

test:
  secret_key_base: 1b44f58c6ff489b6e64ef60b0e22357232a64959e10ac97c9572461d30103e39a66f0418dd2d0540f69dbad8db61c417151136b17a9e312b854de98394864e6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
